#!bin/sh

forbidden_branches=(
	"master"
	"main"
	"develop"
)

current_branch="$(git rev-parse --abbrev-ref HEAD)"

ESC=$(printf '\033')

for branch in "${forbidden_branches[@]}"
	do
		if [ "${current_branch}" = $branch ]; then
			printf "${ESC}[91m%s${ESC}[m\n" "  Cannot commit to ${current_branch} branch."
			exit 1
		fi
	done