name: JS Lint

on: 
  pull_request:
    paths:
      - 'src/**'

env:
  CACHE_TAG: v1

jobs:
  test:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: 22

      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/cache-node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: ESLint
        run: npm run lint:js

      - name: Stylelint
        run: npm run lint:css