name: PHPUnit

on: 
  pull_request:
    paths:
      - 'class/**'
      - 'tests/**'
      - 'admin-bar-tools.php'
env:
  CACHE_TAG: v1

jobs:
  setup:
    name: PHPUnit Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/cache-vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}-${{ matrix.php-version }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: 22
      
      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/cache-node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

  test:
    name: PHPUnit Test
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', 8.2', '8.3',]
        wp-version: ['6.5', '6.6', '6.7', 'master']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup -> PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: 22

      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/cache-vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}-${{ matrix.php-version }}

      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/cache-node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Build React components
        run: npm run build

      - name: Generate .wp-env.override.json
        run: |
          echo '{"config": {},"core": "WordPress/WordPress#${{ matrix.wp-version }}","env": {},"mappings": {},"phpVersion": "${{ matrix.php-version }}","plugins": ["."],"themes": []}' > .wp-env.override.json

      - name: Start wp-env
        run: npm run wp-env start -- --xdebug=coverage

      - name: Run test suite
        run: npm run test:env

      - name: Stop wp-env
        run: npm run wp-env stop
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
